[package]
name = "baad"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
regex = "1.10"
zip = "0.6"
trauma = "2.2"
platform-dirs = "0.3.0"
clap = { version = "4.5.34", features = ["derive"] }
