[package]
name = "baad"
version = "2.0.0"
edition = "2024"

[lib]
name = "baad"
path = "src/lib.rs"

[[bin]]
name = "baad"
path = "src/main.rs"

[dependencies]
reqwest = "0.12.20"
regex = "1.11.1"
anyhow = "1.0.98"

